### ISSUE TITLE
got error and i cant uncuff,watch image below

### ISSUE THREAD

**Issue by xXG3m3Xx** [cshonza/fivem-thiefmenu#1]
[https://imgur.com/zOErFqH](url)
[https://imgur.com/QAqX5MX](url)

**Comment by cshonza** [comment]
I see I'm gonna fix it give me a moment.

**Comment by cshonza** [comment]
What version do you use? With item or without item?

**Comment by cshonza** [comment]
Found it, it will be fixed in a minute.

**Comment by cshonza** [comment]
Issue fixed, thx for reporting 👍

**Comment by xXG3m3Xx** [comment]
> Found it, it will be fixed in a minute.

ty bro,there are some way to add you on discord? i have some question

**Comment by cshonza** [comment]
Yes, add me here: cshonza#0507
