### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JucieWrld999** [cshonza/fivem-thiefmenu#2]
How could i do away with the menu and register each of these as a /chat command instead? I am using a Circle menu and it reads from chat commands. I'm not to familiar with Lua code  :(

**Comment by cshonza** [comment]
Hello, you need to replace function on lines 18-26 by a function that open the menu by a chat command, I will try to create it for you give me a moment.

**Comment by cshonza** [comment]
RegisterCommand("COMMANDHERE", function()
	while true do
        Citizen.Wait(0)
	    local playerPed = GetPlayerPed(-1)
        if not IsEntityDead(playerPed) then
			OpenSearchActionsMenu()
        end
    end
end)

if you replace lines from 18 to 26 by this code it should work, I didn't tested it, if it gives you any error tell me and I will fix it.

**Comment by JucieWrld999** [comment]
Thank you for the very fast reply!  What i'm needing is to register the actions as a chat command and disable the menu completely. For an example: /cuff , /uncuff , /drag , /PutInCar /PullOutCar . The reason for this is because im using a Radial circle menu and once the buttons are clicked they preform a chat commad. To give you an idea take a look at my menu. 
![7a7adfc229c788fda03f39c1af2483d2decd94c8](https://user-images.githubusercontent.com/70625221/92039521-cc517d00-ed3a-11ea-9549-f592cbf152a7.jpeg)

**Comment by cshonza** [comment]
Hello,
It's easy, here is an example of how to do it: 
`
RegisterCommand("search", function()
    	local closestPlayer, closestDistance = ESX.Game.GetClosestPlayer()
        if closestPlayer ~= -1 and closestDistance <= 3.0 then
            TriggerServerEvent('esx_okradanie:message', GetPlayerServerId(closestPlayer), ('You are being searched'))
            OpenBodySearchMenu(closestPlayer)
        else
		ESX.ShowNotification('No players nearby!')
	end
end)
`

If you don't know how to do other things to commands I can do it for you, if you want to use it for everything you need to remove this  https://github.com/cshonza/fivem-thiefmenu/blob/withitem/client/main.lua#L28-L79

**Comment by cshonza** [comment]
Oh the code is in one line, I don't know why so I put it here: https://pastebin.com/hhUhs87S

**Comment by JucieWrld999** [comment]
Thank you! Would you mind if i add you on discord for further questions/help ? Whats your discord name#

**Comment by cshonza** [comment]
Yes, add me cshonza#0507
