### ISSUE TITLE
Player inventory is not showing up

### ISSUE THREAD

**Issue by InLoveWithLua** [cshonza/fivem-thiefmenu#3]
Hello sir im using KRZ Personaml Menu with inventory on my Server.
Police Job is working fine but on your script the Player menu doesnt show up. so players cant rob other player.
No errors in console.

Maybe its a problem with this: 

function OpenBodySearchMenu(player)
	TriggerEvent("esx_inventoryhud:openPlayerInventory", GetPlayerServerId(player), GetPlayerName(player))
end

Could you help me to fix the problem please i like your script. It would be very cool on our Server.

Greetings Marble

**Comment by cshonza** [comment]
Sure, can you send me a screenshot where you got your inventory open? (you should have one of these two on this photo: 
![image](https://user-images.githubusercontent.com/66823451/100446912-e8ea2080-30af-11eb-93b9-5c571d739440.png) )

**Comment by cshonza** [comment]
Oh sorry, I didn't read it carefully, you use KRZ personal menu inventory, give me a moment, I will take a look at it.

**Comment by cshonza** [comment]
Ok, this is a bit harder for me, because KRZ personal menu use Rage UI and I never used it, but I think that I can make it work. And before I will take a look at details I need to warn you that cheaters will be able to use that triggerevent too if they got dumper they can dump it and take a look for the trigger event.

**Comment by cshonza** [comment]
Before I start working on anything, can anyone who works as police at your server search peoples?

**Comment by cshonza** [comment]
If they can I can find a better solution than using triggerevents

**Comment by InLoveWithLua** [comment]
Hello sir thanks for the fast respond! Yes Police can search players. Would be cool if you can manage to make it work

**Comment by cshonza** [comment]
No problem, there is an easy solution, you need to copy this: https://github.com/esx-framework/esx_policejob/blob/master/client/main.lua#L450-L504 (from this link or from your police job) inside that OpenBodySearchMenu function and add this: https://github.com/esx-framework/esx_policejob/blob/master/server/main.lua#L150-L189 to server/main.lua (in thiefmenu script) and then it should work, there will maybe be some errors, unfortunately, I'm not able to test it for you so you need to do it if you need it now.

**Comment by InLoveWithLua** [comment]
i will try it out man thank you:D!

**Comment by cshonza** [comment]
No problem, tell me if it will work after you try it.
