### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ProsteMartin** [cshonza/fivem-thiefmenu#5]
Ahoj, mám problém s tím že nemůžu dát člověka do auta, pokuď je to chyba u mě prosím o pomoc.

Hi. I have a problem with the fact that I can't put a person in the car, if it's a mistake, please help me.

**Comment by cshonza** [comment]
Ahoj, potřeboval bych vědět, jaký script na inventář používáš, poté ti dokáži pomoct blíže.

**Comment by cshonza** [comment]
Dále mi také pomůže, když mi řekneš zda ti u policejobu funguje prohledávání (pokud ho používáš)

**Comment by cshonza** [comment]
Jestli funguje prohledávání u policejobu ale v thiefmenu ne tak doporučuji zkusit toto: https://github.com/cshonza/fivem-thiefmenu/issues/3 mělo by to fungovat, nejspíš ale udělám ještě jeden release kde kód na tuto verzi upravím.

**Comment by ProsteMartin** [comment]
esx_inventoryhud
Funguje
V thiefmenu funguje prohledávání ale nefunguje dávání do auta

**Comment by cshonza** [comment]
Omlouvám se, špatně jsem koukl na to, co jste psal. Podívám se na to a dám vědět. Potřebuji ale také vědět, jakou verzi thiefmenu používáte (s itemem nebo bez itemu)

**Comment by ProsteMartin** [comment]
Bez itemu

**Comment by cshonza** [comment]
Dobře, kouknu na to hned co budu mít čas, dejme tomu, že o víkendu bych to opravil, pokud by se jednalo o chybu ve scriptu. Pokud ne tak bych se pokusil zjistit, proč Vám to nefunguje.

**Comment by cshonza** [comment]
Jak na to teď koukám, tak vidím, že osoba musí mít pouta, dával jste do auta osobu s pouty nebo bez nich (myslím tím zda měla osoba nasazená pouta) ? Pokud bez tak prosím zkuste i s pouty. Pokud chcete osobu dávat do auta bez nutnosti pout tak mohu provést úpravu a zaslat ji zde.

**Comment by ProsteMartin** [comment]
Zkoušel jsem to ja bez pout tak i s pouty a nic nefungovalo.

**Comment by cshonza** [comment]
Ahoj, omlouvám se za čekání, bohužel aktuálně nemám možnost tuto funkci otestovat, jelikož mám localhost a nemám veřejnou IP, tudíž se na server nemůže napojit další osoba. Zkusím ti ale pomoct i bez zkoušení scriptu. Potřeboval bych vědět jestli ti jde dát někdo do auta na tvém serveru pokud používáš F6 u policejobu.

**Comment by ProsteMartin** [comment]
Ano, jde.

**Comment by cshonza** [comment]
Tak v tom případě potřebuji vědět, jaký policejob používáš, nejlépe pokud by jsi mi ho mohl poslat. Pokud ho nechceš posílat takhle veřejně na github issue tak řekni. Popřípadě můžeme jít na discord a tam bych ti řekl co udělat, aby to fungovalo. Pokud by jsi mi ho ale poslal tak to dokážu udělat.

**Comment by ProsteMartin** [comment]
Zde.
[esx_policejob.zip](https://github.com/cshonza/fivem-thiefmenu/files/5792503/esx_policejob.zip)
